Feat/create page
uwebury/trip-trove pull request #13
Opened 2024-01-17 14:08 UTC by markusgemeinder

Create Form component and add buttons

2024-01-17 14:28 UTC, moonwave99 requested changes

2024-01-17 14:28 UTC, moonwave99 commented on components/Form/index.js
> +    document.getElementById("tripForm").elements.destination.focus();
No vanilla DOM selections in react ^^
A solution is to use [useRef](https://react.dev/reference/react/useRef):

```js
const formRef = useRef(null);

const handleReset = (event) => {
    event.preventDefault();
    formRef.current.reset();
    formRef.current.elements.destination.focus();  
}

return (
  <FormContainer ref={formRef}>...</FormContainer>
);
```

2024-01-17 14:28 UTC, moonwave99 commented on components/NavigationButton/index.js
> +    <>
No diamonds for a lonely child

(sounds like a great '70ies folk album btw)

2024-01-17 14:56 UTC, CJAkkuec approved these changes

2024-01-17 15:45 UTC, moonwave99 approved these changes

2024-01-17 16:13 UTC, moonwave99 approved these changes

2024-01-18 07:37 UTC, moonwave99 requested changes

2024-01-18 07:37 UTC, moonwave99 commented on components/Form/index.js
`data.start` and `data.end` now!

2024-01-18 09:03 UTC, merged