Feat/edit functionality
uwebury/trip-trove pull request #21
Opened 2024-01-24 13:28 UTC by uwebury

Created edit functionality, implemented toast messages and moved validateTripDates function to utils.
[US7 - Edit Functionality](https://github.com/uwebury/trip-trove/issues/2)

2024-01-24 16:26 UTC, moonwave99 requested changes

2024-01-24 16:26 UTC, moonwave99 commented on next.config.js
> +      },
I think you can do `*.unsplash.com`, let me know if it works!

2024-01-24 16:26 UTC, moonwave99 commented on components/Form/index.js
> +          >
If you don't add `type="button"`, the form submit event gets triggered as well

2024-01-24 16:26 UTC, moonwave99 commented on components/Form/index.js
> +  };
The best way to achieve this feature is by using controlled inputs and a local state that defaults to the data passed via props - [see example](https://stackblitz.com/edit/vitejs-vite-cjxjdw?file=src%2FApp.jsx):

```jsx
function DirtyForm({ data, onSubmit }) {
  const [dirtyData, setDirtyData] = useState(data);

  function handleInput(event) {
    setDirtyData((prev) => ({
      ...prev,
      [event.target.name]: event.target.value,
    }));
  }

  function handleSubmit(event) {
    event.preventDefault();
    onSubmit(dirtyData);
  }

  function handleDiscard() {
    setDirtyData(data);
  }

  return (
    <form onSubmit={handleSubmit} className="box">
      <h1>Dirty Fields Example</h1>
      <label>
        Name{' '}
        <input
          name="name"
          value={dirtyData.name}
          onInput={handleInput}
          required
          placeholder="Your Name"
        />
      </label>
      <label>
        Email
        <input
          type="email"
          name="email"
          value={dirtyData.email}
          onInput={handleInput}
          required
          placeholder="Your E-Mail"
        />
      </label>
      <button type="button" onClick={handleDiscard}>
        Discard
      </button>
      <button>Send</button>
    </form>
  );
}

```

2024-01-24 16:51 UTC, Roland-Hufnagel reviewed
switched to Diego...

2024-01-24 19:34 UTC, markusgemeinder commented on next.config.js
> +      },
It works, thanks Diego!

2024-01-25 07:38 UTC, moonwave99 approved these changes

2024-01-25 12:14 UTC, Roland-Hufnagel requested changes
Please can you once more look at my comments? It needs a bit of refactoring.

2024-01-25 12:14 UTC, Roland-Hufnagel commented on components/ToastMessage/index.js
> +  originalData,
I am not really sure if you need this data here. In my mind you only pass two functions to be executed for each choice. Maybe I'm wrong but can you explain it to me?

2024-01-25 13:43 UTC, markusgemeinder commented on components/Form/index.js
> +        ref={formRef}
We did discuss this with Diego in an early user story. He recommended us to use formRef (instead of an id) for resetting the form by clicking the Reset button. 

Refactoring to handleReset(event) and event.target.reset or .focus wouldn't fix the problem, because the event is clicking the Reset button.

Function handleReset() needs formRef, unless you recommend a different solution which we would appreciate.

2024-01-25 16:34 UTC, Roland-Hufnagel approved these changes
Looks good now.

2024-01-26 08:05 UTC, merged