Feat/packing list part 1
uwebury/trip-trove pull request #34
Opened 2024-02-01 15:23 UTC by uwebury

Changed packing list from string to array so that user can add items and quantity to their packing list.
We decided to add two fields (itemName and itemQuantity) instead of just one field as originally described in [US11 - Enhanced Packing List Management](https://github.com/uwebury/trip-trove/issues/18)

2024-02-02 10:41 UTC, F-Kirchhoff requested changes
Hey!
looks already great. You only need to change your deletion of packingList items, which should not mutate a value and can be done in a more readable way.

2024-02-02 10:41 UTC, F-Kirchhoff commented on components/Form/index.js
> +        packingList: updatedPackingList,
here you are mutating the "updatedPackingList". Use filter here instead: 
```js
const updatedPackingList = prev.packingList.filter((item, itemIndex) => itemIndex !== index)
```
you can after that add a default item if you need to before returning the updated Handoverdata.

2024-02-02 10:41 UTC, F-Kirchhoff commented on components/Form/index.js
> +                    Math.max(0, parseInt(event.target.value))
you can give the number input the min and max values then you don't need to check it yourself.

2024-02-02 10:41 UTC, F-Kirchhoff commented on components/Form/index.js
> +                  textColor={"var(--color-add-button-text)"}
it would be better if the user of this component (the dev) would not need to know the specific variable names from the css. You would need to update these values if you decide to change the names of the variables later on. Generally, you would define "variants" inside the styled component for "delete" "add" etc. Have a look into the handout of styled-components 2

2024-02-02 10:41 UTC, F-Kirchhoff commented on components/PackingList/index.js
> +          <li key={index}>
don't use the index as the key. The key must be directly connected to the rendered element, neverchanging and unique.

2024-02-02 10:41 UTC, F-Kirchhoff commented on components/PackingList/index.js
> +              : ""}
you can just use `item.itemQuantity ? ... : ...`

2024-02-02 11:06 UTC, uwebury commented on components/Form/index.js
> +        packingList: updatedPackingList,
Thank you for your suggestion.

We have tested to filter but this leads to an unwanted user experience: If there are multiple items on the packing list and one is removed it will also remove all items below that one.
E. g. 3 items > 2nd item is deleted > 3rd item is deleted, too.

We can discuss whether there is a solution but in our opinion it seems that we would have to need to change more. (In particular, since we have implemented a Discard button that also depends on handoverData.)

2024-02-02 11:32 UTC, uwebury commented on components/Form/index.js
> +                  textColor={"var(--color-add-button-text)"}
Thank you.

We're not sure what you mean here exactly: We checked the [handout](https://github.com/neuefische/cgn-web-23-4/blob/main/sessions/react-styled-components-2/react-styled-components-2.md) and think that you're suggesting to hardcode each button separately in Form.styled.js. Can you confirm or give us more information for clarity on how to proceed here?

2024-02-05 09:44 UTC, uwebury commented on components/Form/index.js
> +        packingList: updatedPackingList,
As discussed on Friday, we have replaced in key index by objectID to have unique key and also to make sure that deleting a packing list item works as expected.
In doing so, it was necessary to refactor the code a little bit.

2024-02-06 08:22 UTC, CJAkkuec commented
LGTM 🚀

2024-02-06 09:18 UTC, merged