Feat/packing list part 2
uwebury/trip-trove pull request #36
Opened 2024-02-06 14:13 UTC by uwebury

Added functionality for user to add predefined packing list as starting points for more convenient planning. Changes are based on [US - Packing List Presets (Templates / Categories)](https://github.com/uwebury/trip-trove/issues/29) with the following adjustments mostly due to time constraints:

- The user cannot adjust/save new presets.
- Presets have been hardcoded. They're not coming from/stored in MongoDB.
- User will not see items on the list before applying them.
- Plus button for adding items is due to a refactoring below the itemName field. (Will be fixed in an upcoming user story that bundles fixing some design/usability issues.)

2024-02-06 14:53 UTC, CJAkkuec requested changes
Very good! I like where this is headed. I think you likely _could_ add a preview of the items in the templates or add a summary/description to make the process less opaque in the future. It doesn't need to be part of this US though.

Just a couple of small changes. 👍

2024-02-06 14:53 UTC, CJAkkuec commented on components/Form/Form.styled.js
> +  gap: 10px; // Adjust the gap as needed
```suggestion
  gap: 10px;
```
Please remove comments from code you want to deploy. :)

2024-02-06 14:53 UTC, CJAkkuec commented on components/Form/index.js
> +import React, { useState } from "react";
```suggestion
import { useState } from "react";
```
No need to import `React`.

2024-02-06 14:53 UTC, CJAkkuec commented on components/Form/index.js
> +            <option value="ThreeWeeks">Three weeks</option>
```suggestion
            <option value="weekend">Weekend</option>
            <option value="one week">One week</option>
            <option value="two weeks">Two weeks</option>
            <option value="three weeks">Three weeks</option>
```
The `value` attribute represents the value passed to the property with the respective `name` attribute (here: "template"), hence why it can be a regular string. This aids the readability of your database. :)

2024-02-07 09:32 UTC, JuliaSchw approved these changes

2024-02-07 09:43 UTC, merged